######## Global message variables: ########
#
## The player who executed the command
## <sourceplayer>          - The name of the player who executed the command, if console will return "Console".
## <sourceip>              - The ip of the player who executed the command, if console will return "127.0.0.1"
## <sourceuuid>            - The uuid of the player who executed the command, if console will return "null"
#
## The player who is the target of the command/automated check, if there is no target they will all return null.
## <targetplayer>          - The name of the player who is the target of the command, if there is no target it will return null.
## <targetip>              - The ip of the player who is the target of the command, if there is no online target it will return null.
## <targetuuid>            - The uuid of the player who is the target of the command, if there is no target it will return null
#
#
## Colour codes:
## &0	BLACK
## &1	DARK BLUE
## &2	DARK GREEN
## &3	DARK AQUA
## &4	DARK RED
## &5	DARK PURPLE
## &6	GOLD
## &7	GRAY
## &8	DARK GRAY
## &9	INDIGO
## &A   GREEN
## &B	AQUA
## &C	RED
## &D	PINK
## &E	YELLOW
## &F	WHITE
## &M	STRIKE THROUGH
## &N	UNDERLINED
## &L	BOLD
## &K	RANDOM
## &O	ITALIC

# Only change this value if you have manually added new config entries and want to remove the console warning
config-version: "00002"

# Settings related to the anti-mcleaks part of the plugin
mcleaks:
  join-check:
    # Automatically check joining players against the mcleaks database
    enable-join-check: true

    # Actions to take when an error occurs and a player can't be checked
    error:
      notify: true
      notification: "&6An error occurred while automatically checking &e<targetplayer>&6 in the MCLeaks database."
      execute-command: true
      command: "mail send admin Error occured checking <targetplayer>"

    # Actions to take when a player is not on the confirmed mcleaks list
    not-mcleaks:
      notify: false
      notification: "&e<targetplayer>&6 is &2NOT &6on the list of confirmed MCLeaksChecker accounts although may still be one."
      execute-command: false
      command: "setgroup <targetplayer> Trusted"

    # Actions to take when a player is on the confirmed mcleaks list
    is-mcleaks:
      notify: true
      notification: "&e<targetplayer>&6 &cIS &6on the list of confirmed MCLeaks accounts."
      execute-command: true
      command: "ban <targetplayer> Using a stolen/hacked account."

vpnshield:
  # API key, register on https://iphub.info/ and add a subscription. Free subscriptions come with a 1000 queries per day limit, other plans are available.
  api-key: ""
  # The VPN blocker is toggled on at server start. Not recommended if you get 1000 joins every day.
  enable-by-default: false

  # Start with increased sensitivity level (may result in false positives, check https://docs.iphub.info/documentation/json-keys/ for more info)
  increased-default-sensitivity: false;

  # Actions to take when an error occurs and a player can't be checked
  error:
    notify: true
    notification: "&6An error occurred while automatically checking &e<targetplayer>&6 against VPN database."
    execute-command: true
    command: "mail send admin Error occured checking <targetplayer>"

  # Actions to take when a player is not using a vpn
  not-vpn:
    notify: true
    notification: "&e<targetplayer>&6 is &2NOT &6on using a VPN according to current filters."
    execute-command: false
    command: "setgroup <targetplayer> Trusted"

  # Actions to take when a player is using a vpn
  using-vpn:
    notify: true
    notification: "&e<targetplayer>&6 &cIS &6using a VPN according to current filters."
    execute-command: true
    command: "kick <targetplayer> Using a VPN or proxy is not allowed. Turn it off and try again."

  # Send a message to a player bypassing the using-vpn command
  bypass:
    notify: true
    notification: "&6You have bypassed VPNShield."

# Settings for command responses
commands:

  # /help
  help:
  - "AltFinder commands:"
  - "/ip (player) - Prints the current IP of a player."
  - "/mcleaks (player) - Checks a player account against a database of confirmed MCLeaksChecker hacked accounts. Player must have joined the server at some point"

  # /ip
  ip:
    self: "&6Your current IP address is &e<sourceip>&6."
    other: "&6The player's current IP address is &e<targetip>&6."
    no-such-player: "&6That player is not currently online."

  # /mcleaks
  mcleaks:
    error: "&6An error occurred fetching player from MCLeaksChecker database, try again later."
    not-found: "&e<targetplayer>&6 is &2NOT &6on the list of confirmed MCLeaks accounts although may still be one."
    found: "&e<targetplayer>&6 &cIS &6on the list of confirmed MCLeaksChecker account."
    no-such-player: "&e<targetplayer> &6has not joined the server before."

  # General command feedback, target player variables do not work here
  no-perm: "&cYou do not have permission to do that."
  invalid-usage: "&cInvalid command usage."
