name: AltFinder
version: 0.0.3
author: Karl Essinger (KarlofDuty)
website: http://karlofduty.com
main: com.karlofduty.altfinder.AltFinder
commands:
  ip:
    description: Shows the IP of the player provided
    usage: /ip (player)
  mcleaks:
    description: Checks if a user is an mcleaks stolen account.
    usage: /mcleaks <player>
  vpnshield:
    description: Toggles VPNShield or VPNShield's strictmode
    usage: /vpnshield [on/off/toggle] or /vpnshield strictmode [on/off/toggle]
permissions:
  altfinder.*:
    description: Gives access to all commands.
    default: false
  altfinder.ip.*:
    description: Gives acces to all versions of the /ip command.
    default: op
  altfinder.ip.self:
    description: Gives acces to using the /ip command on themselves.
    default: true
  altfinder.ip.other:
    description: Gives acces to using the /ip command on others.
    default: op
  altfinder.mcleaks.*:
    description: Gives acces to all mcleaks features.
    default: op
  altfinder.mcleaks:
    description: Gives acces to the /mcleaks command.
    default: op
  altfinder.mcleaks.notify:
    description: Sends all mcleaks notifications to these players.
    default: op
  altfinder.vpnshield.notify:
    description: Sends all vpnshield notifications to these players.
    default: op
  altfinder.vpnshield.bypass:
    description: Player can join with VPN while VPNShield is on.
    default: op
  altfinder.vpnshield.toggle:
    description: Player can toggle VPNShield.
    default: op
  altfinder.vpnshield.strictmode.toggle:
    description: Player can toggle strict mode.
    default: op